# Generated by Django 3.2.10 on 2024-01-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Categorynow',
            new_name='Category',
        ),
    ]
